### ISSUE TITLE
Enhancement:  Support for Nomad Volumes

### ISSUE THREAD

**Issue by rejackson73** [terraform-providers/terraform-provider-nomad#102]
With support for CSI storage, Terraform provider for Nomad needs to support registration of Volumes.  Full parameter set for Volumes are located in the [Nomad Volume Register documentation](https://www.nomadproject.io/docs/commands/volume/register/).

Terraform v0.12.24
provider.nomad v1.4.5
Nomad v0.11.0

**Comment by jrasell** [comment]
Hi @rejackson73 and thanks for taking the time to raise this issue. This would be a great addition and has been marked as an enhancement accordingly.
