### ISSUE TITLE
nomad_job (batch) fails to return allocation_ids

### ISSUE THREAD

**Issue by mahsoud** [terraform-providers/terraform-provider-nomad#109]
Terraform v0.12.24
provider.nomad v1.4.6
Nomad v0.11.1

Terraform Configuration Files:
```hcl
provider nomad {
  address   = var.NOMAD_ADDR
  secret_id = var.NOMAD_TOKEN
}

resource nomad_job this {
  jobspec                 = file("${path.module}/nomad_job.tpl")
  deregister_on_destroy   = true
  deregister_on_id_change = true
  detach                  = false
}

```

Sample job file:
```hcl
job "scenario-validation" {
  datacenters = ["mio"]
  type = "batch"

  group "testing" {
    task "test" {

      driver = "raw_exec"
      config {
        command = "powershell.exe"
        args = [
          "-NoProfile",
          "-ExecutionPolicy",
          "Bypass",
          "-Command",
          "Write-Host",
          "Hello"
        ]
      }

      template {
        destination   = "sample.csv"
        data          = <<EOH
sample
EOH
      }
      
      restart {
        attempts = 1
        mode     = "fail"
      }
    }
  }
}

```

Affected Resource:
- nomad_job

Debug Output:
- terraform: https://gist.github.com/mahsoud/62701edfa8440dd8854c0d018afac863
- nomad: https://gist.github.com/mahsoud/722702b6197ead29ad3729edbbbd593b

Expected Behavior:
Job to be created, and allocation_ids retuned.

Actual Behavior:
the job is created, however fails to return allocation ids.

Console output:

nomad_job.this: Creating...
nomad_job.this: Still creating... [10s elapsed]
nomad_job.this: Still creating... [20s elapsed]
Error: error waiting for job 'scenario-validation' to deploy successfully: Unexpected response code: 404 (eval not found)

Steps to Reproduce
1. `terraform apply -auto-approve`

References:
- https://github.com/terraform-providers/terraform-provider-nomad/issues/104#issuecomment-630902627_

**Comment by cgbaker** [comment]
Can you run `TF_LOG=8 terraform apply -auto-approve`? Also, what is the status of `nomad job status -verbose scenario-validation` after the failure? It appears that the evaluation has been GC'd sometime between one check and the next.

**Comment by mahsoud** [comment]
Hey,
As far as I understand TF_LOG=8  is invalid and is equivalent to TF_LOG=TRACE?

I've also set TF_LOG_PATH to a local file, the content is here:https://gist.github.com/mahsoud/62701edfa8440dd8854c0d018afac863

The evaluation indeed seems to be GC'd almost immediately, maybe you could advise me how to deal with that :p ?

**Comment by cgbaker** [comment]
The good news is that the current bug, where the provider is looping waiting for a non-existent deployment, seems to be exacerbating the issue by allowing enough time for the job to complete. This would happen if `eval_gc_threshold` was very short or there is a manual GC call.

Can I ask why you're using `detach = false`?

**Comment by mahsoud** [comment]
> Can I ask why you're using `detach = false`?

I use allocation_ids to check the status of the last allocation using script & null_resource

**Comment by mahsoud** [comment]
Confirmed with my team that eval_gc_threshold is set to default 1 hour; however I do not see terminal allocations, they seem to be garbage collected seconds after completing.

**Comment by cgbaker** [comment]
is the job GC'd as well?

**Comment by cgbaker** [comment]
The client logs indicate that the server removed the allocation. Can you provide the server logs as well? Does this happen repeatedly, or was this a one-time bad luck?

**Comment by mahsoud** [comment]
It does happen consistently, now with v1.4.6.
I did notice the issue on older builds, but they were rare. 

I'll be able to troubleshoot it further early next week. Will update settings on the client-side, to make sure GC is not triggered as often and will try to reproduce the issue with a server under my control. Thank you.

**Comment by mahsoud** [comment]
Reproduced the issue with v1.4.6 on a test nomad instance, to ensure allocation is not GC'd :)

Terraform exited with error after 5 min timeout:
```
Error: error waiting for job 'scenario-validation' to deploy successfully: couldn't find resource (21 retries)

  on main.tf line 11, in resource "nomad_job" "this":
  11: resource nomad_job this {
```

Log files:
Terraform: https://gist.github.com/mahsoud/6e690e67f1f8d313501f602bbba50788
Nomad Agent: https://gist.github.com/mahsoud/0b710f505d541a9e229dbc461a4b02e8


Seems that the only issue here is indeed the fact that provider is looping waiting for a non-existent deployment

**Comment by cgbaker** [comment]
Would you mind trying 1.4.7?

**Comment by mahsoud** [comment]
how did I miss release :) looks good to me, thank you!
