### ISSUE TITLE
Nomad jobspec "task =" line in service stanza causes a parsing error

### ISSUE THREAD

**Issue by shannonmcin** [terraform-providers/terraform-provider-nomad#134]
### Terraform Version
Terraform v0.12.24

### Nomad Version
Nomad v0.12.0-beta2 (5b80d4e638f1a27eee3ca245f8babb115e4c098d)

### Provider Configuration

```hcl
provider "nomad" {
  address = "http://127.0.0.1:4646"
  version = "~> 1.4"
}
```
We are using version 1.4.8 of the provider, from the [hashicorp release listing](https://releases.hashicorp.com/terraform-provider-nomad/1.4.8/).

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "runtime" {
  jobspec = templatefile("/runtime.tmpl", {})
}
```

in runtime.tmpl:

```hcl
service {
  name = "runtime"
  port = "cluster"
  task = "bootstrap"
  connect {
    native = true
  }
}
```

### Debug Output

```
Error: error parsing jobspec: error parsing 'job': 1 error occurred:
	* group: 'runtime', service (0): invalid key: task

  on .terraform/modules/runtime/main.tf line 1, in resource "nomad_job" "runtime":
   1: resource "nomad_job" "runtime" {
```

### Expected Behavior
The jobspec including the above snippet is valid; `nomad plan` plans it successfully, and if I paste the templated jobspec into the Nomad web UI, it runs. The nomad provider should successfully apply it.

### Actual Behavior
Terraform gives the error show above under Debug Output. When I remove the line `task = "bootstrap"`, Terraform functions as expected, so that line is the problem. 

Currently, we are using a beta version of Nomad; will the Terraform Nomad provider wait for the next major release of Nomad to catch up with the new features?

### Steps to Reproduce
Include the line `task = "anything"` in the jobspec for a `nomad_job` resource.

**Comment by cgbaker** [comment]
thanks for the report @shannonmcin , the 1.4.8 provider should support all of the Nomad 0.12.0 API. i'm looking into this now.

**Comment by cgbaker** [comment]
hi @shannonmcin , i wasn't able to reproduce this locally. can you provide me the output of `terraform -v`?

**Comment by shannonmcin** [comment]
I'm not getting it either anymore; I cleared out the state on my machine and re-downloaded the Nomad provider, Terraform, etc., and a resource with the same jobspec does successfully get applied. I must have had an old version of the provider, but thought I had the most recent. So sorry about that, but thanks so much for your quick response!
