### ISSUE TITLE
import for nomad_job

### ISSUE THREAD

**Issue by Legogris** [terraform-providers/terraform-provider-nomad#135]
The docs don't mention anything re importing existing nomad_job resources into state.
Is this supported but not documented, or a missing feature?

**Comment by Legogris** [comment]
Simply not supported was easily verified, closing this.

**Comment by lgfa29** [comment]
Thank you for bring this to our attention. We currently don't support importing any resource, but I don't see any reason for this. 

I created an issue (#137) so we can track this.
