### ISSUE TITLE
Add support for service check failures_before_critical

### ISSUE THREAD

**Issue by Legogris** [terraform-providers/terraform-provider-nomad#139]
When doing plan:

```
Error: error parsing jobspec: error parsing 'job': 1 error occurred:
        * group: 'g', task: 't', service (1): 's', check -> invalid key: failures_before_critical
```

https://www.nomadproject.io/docs/job-specification/service.html#failures_before_critical

**Comment by lgfa29** [comment]
Thanks for the report @Legogris. 

I just released a version that supports these new values from Nomad 0.12.2.
