### ISSUE TITLE
check_restart which was added in Nomad 0.7 is not supported

### ISSUE THREAD

**Issue by bookwar** [terraform-providers/terraform-provider-nomad#16]
### Terraform Version

Terraform v0.10.7

### Affected Resource(s)

- nomad_job

### Terraform Configuration Files
```hcl
resource "nomad_job" "my_job" {
  jobspec = "${data.template_file.my_template.rendered}"
}
```

Job spec with [check_restart](https://www.nomadproject.io/docs/job-specification/check_restart.html):
```hcl
job "my_job" {

  ...

  type = "service"

  group "my_group" {
    task "my_task" {
 
      ...

      service {
        name = "my_service"

        check {
          type     = "tcp"
          name     = "app_port"
          interval = "1s"
          timeout  = "1s"
        }

        check_restart {
           limit = 3
           grace = "90s"
           ignore_warnings = false
        }
      }
      ...
    }
  }
}

```

### Expected Behavior
After running `terraform apply` new deployment starts

### Actual Behavior
`terraform apply` produces an error

```
* nomad_job.my_job error parsing jobspec: error parsing 'job': 1 error(s) occurred:

* group: my_group', task: 'my_task', service (1) -> invalid key: check_restart

```

### References
Issue looks similar to https://github.com/terraform-providers/terraform-provider-nomad/issues/11
So probably update to nomad 0.7 is required.

**Comment by NikolaeVarius** [comment]
+1

**Comment by ole-lukoe** [comment]
+1, please update jobspec

### Terraform Version
Terraform v0.11.3
provider.nomad v1.1.0

### Actual Behavior
```
* nomad_job.my_job: error parsing jobspec: error parsing 'job': 1 error(s) occurred:
* group: 'my_group', task: 'my_task', service: 'my_service', check -> invalid key: header
```

**Comment by unitrq** [comment]
+1
Vendored nomad version is 0.6.0, it fails to parse service checks defined for nomad ^0.7

**Comment by sergey-jerzy** [comment]
+1

**Comment by paddycarver** [comment]
With the release of 1.2.0, we've synced this with Nomad 0.7.1, which should resolve the issue. If not, please feel free to comment here, and we'll reopen it again and figure it out. Thanks!

**Comment by ole-lukoe** [comment]
Please update jobspec again:  progress_deadline parameter was added in Nomad 0.8.4.
Thanks in advance!
