### ISSUE TITLE
check -> invalid key: address_mode

### ISSUE THREAD

**Issue by perbly** [terraform-providers/terraform-provider-nomad#31]
Hi

address_mode was added in Nomad 0.7.1 but nomad terraform provider 1.1 seems to lack support for it.

If i run nomad run on the same hcl job it works but terraform apply fails with this error:

`group: 'deathstar-service', task: 'deathstar-service', service: 'deathstar-service', check -> invalid key: address_mode`

### Terraform Version
v0.11.3

### Nomad provider versio
v.1.1.0

### Terraform Configuration Files
```hcl
      service {
        name = "deathstar-service"
        address_mode = "driver"
        port = 4747
        tags = [
            "prod"
            ,"ops"
        ]
        check {
            type     = "tcp"
            interval = "30s"
            timeout  = "30s"
            address_mode = "driver"
            port  = 4747
        }
      }
```

/Per

**Comment by Dirrk** [comment]
Instead of creating a duplicate issue, I just wanted to point out that the method key is also not correct.  I imagine this due to the same issue.


`* group: 'service', task: 'nginx', service: 'nginx-auth', check -> invalid key: method`

```
service {
        name = "nginx-auth"
        port = "nginx"

        check {
          type     = "http"
          method   = "GET"
          protocol = "http"
          path     = "/hello"
          port     = "nginx"
          interval = "10s"
          timeout  = "2s"
        }
      }
```

**Comment by paddycarver** [comment]
With the release of 1.2.0, we've synced this with Nomad 0.7.1, which should resolve the issue. If not, please feel free to comment here, and we'll reopen it again and figure it out. Thanks!
