### ISSUE TITLE
Terraform does not create Sentinel policy if not already created

### ISSUE THREAD

**Issue by amanjeev** [terraform-providers/terraform-provider-nomad#38]
### Terraform Version

`0.11.7`

### Plugin version

`1.2.0`

### Affected Resource(s)
Please list the resources as a list, for example:
- nomad_sentinel_policy

### Terraform Configuration Files
```hcl
resource "nomad_sentinel_policy" "exec-only" {
  name = "exec-only"
  description = "Only allow jobs that are based on an exec driver."
  policy = <<EOT
main = rule { all_drivers_exec }

# all_drivers_exec checks that all the drivers in use are exec
all_drivers_exec = rule {
    all job.task_groups as tg {
        all tg.tasks as task {
            task.driver is "exec"
        }
    }
}
EOT
  scope = "submit-job"
  # allow administrators to override
  enforcement_level = "advisory"
}
```

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* module.sentinel-policies.nomad_sentinel_policy.exec-only: 1 error(s) occurred:

* nomad_sentinel_policy.exec-only: error reading Sentinel policy "exec-only": Unexpected response code: 404 (Sentinel policy not found)

### Panic Output
N/A

### Expected Behavior
Should create the policy `exec-only`.

### Actual Behavior
Complained that the `Sentinel policy not found` and I had to create the policy manually.

### Steps to Reproduce
1.  Create a Sentinel policy that does not exist in Nomad.
2. `terraform apply`

**Comment by amanjeev** [comment]
I also see issues where the provider plugin fails to notice a change made to the Sentinel policy outside of Terraform.

**Comment by lgfa29** [comment]
> I also see issues where the provider plugin fails to notice a change made to the Sentinel policy outside of Terraform.

The second issue is related to #1, so it will be resolved when that issue is closed.

**Comment by lgfa29** [comment]
Hi @amanjeev, 

I wasn't able to reproduce this issue, so I am closing it for now. 

Let us know if you are still having this problem in the latest version of the provider and we will re-open it.
