### ISSUE TITLE
leader property not supported on tasks

### ISSUE THREAD

**Issue by cstruct** [terraform-providers/terraform-provider-nomad#4]
The Nomad provider does not support the `leader` property on tasks. If the same `jobspec` is submitted to nomad directly it works.

### Terraform Version
`Terraform v0.9.11`

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```hcl
provider "nomad" {
  address = "127.0.0.1: 4646"
}

resource "nomad_job" "test" {
  jobspec = <<EOF
job "test-job" {
  type = "service"
  datacenters = ["dc1"]

  group "test-group" {
    count = "1"

    task "test-task" {
      driver = "docker"

      config {
        image = "hello-world"
      }

      leader = true
    }
  }
}
EOF
}
```

### Debug Output
https://gist.github.com/cstruct/3630a5c93044d579d66898c0a07e0eb5

### Expected Behavior
That Terraform schedules a task that is the leader in the group.

### Actual Behavior
Terraform fails and says leader is an invalid key.

### Steps to Reproduce
1. `terraform apply`

**Comment by cstruct** [comment]
Terraform 0.9.11 was released a long time after [leader was added](https://github.com/hashicorp/nomad/commit/a22f1647f9f636bf4ef5388e7ba8dcf102757ff8) so I don't get why this breaks. I don't write Go myself but I thought it always pulled from master when getting dependencies.

**Comment by sirocode** [comment]
"shutdown_delay" option for Nomad task (introduced in Nomad 0.6.1) also does not work if I place nomad jobs via Terraform 0.10.2.

Also: "update" section for nomad group does not work, I had to comment it out in order to place nomad task via Terraform,:

```
 group "test-nomad" {
    count = 1 
    /*
    update {
      max_parallel     = 1
      canary           = 2
      min_healthy_time = "2m"
      healthy_deadline = "5m"
      auto_revert      = true
    }
    */

...
```

But it works if I just use "nomad run".

**Comment by cstruct** [comment]
@sirocode have you tested if #7 fixes those cases as well? I presume it does, but it would be good to know.

**Comment by sirocode** [comment]
@cstruct I can see that the fix is not yet released. Waiting for release.

**Comment by cstruct** [comment]
I was more thinking of building it from source and trying it out. I'll see if I can manage to do it this evening. Would be nice to know that it fixes all these issues and we don't have to wait for multiple releases.
