### ISSUE TITLE
Validate nomad_job.jobspec using `nomad job validate`

### ISSUE THREAD

**Issue by Xopherus** [terraform-providers/terraform-provider-nomad#54]
### Terraform Version
0.11.11

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files

Say you have a nomad job which is rendered using terraform's `template_file`. The contents of the nomad job don't matter too much, but the fact that it has template syntax in it does.

```hcl
data "template_file" "job_template" {
  template = "${file("./nomad.hcl")}"

  vars {
    git_rev = "${var.git_rev}"
  }
}

resource "nomad_job" "job" {
  jobspec = "${data.template_file.job_template.rendered}"
}
```

### Expected Behavior
What should have happened?

Is it possible to [optionally] run `nomad job validate` on the `nomad_job.jobspec` at the plan phase? Its not possible to do so before the job is rendered because it is a template.

**Comment by ketzacoatl** [comment]
Looks awesome!

**Comment by cgbaker** [comment]
in that case, i'll close this issue.
