### ISSUE TITLE
Add Nomad job HCL to JSON conversion data resource

### ISSUE THREAD

**Issue by analytically** [terraform-providers/terraform-provider-nomad#71]
It would be handy to have a data resource to convert HCL to JSON.

**Comment by cgbaker** [comment]
Interesting. Can you give me a couple of downstream use cases for this?

**Comment by analytically** [comment]
Our usecase is templated jobs for cluster-broccoli (https://github.com/data-science-platform/cluster-broccoli) where it currently only accepts JSON jobs (as Nomad's API speaks JSON only apart from /v1/jobs/parse). We could also try and use the HTTP provider to convert HCL jobs to JSON but it currently doesn't support POST, see https://github.com/terraform-providers/terraform-provider-http/pull/22.

**Comment by analytically** [comment]
See https://github.com/Data-Science-Platform/cluster-broccoli/wiki/Templates. We're running cluster-broccoli as Nomad job and use Nomad's template functionality to drop the templates (after already passing them through Terraform).

**Comment by analytically** [comment]
@cgbaker is this something you'd accept a PR for?

**Comment by cgbaker** [comment]
@analytically , sure!

**Comment by analytically** [comment]
Cluster-broccoli now supports HCL templates directly.
