### ISSUE TITLE
Create data source for ACL token

### ISSUE THREAD

**Issue by lgfa29** [terraform-providers/terraform-provider-nomad#85]
# nomad_acl_token

Get information on an [ACL token](https://www.nomadproject.io/api/acl-tokens.html#read-token). 

**Important:** this data source will store tokens in the Terraform state. The documentation should have a warning like the [one in the resource page](https://github.com/terraform-providers/terraform-provider-nomad/blob/master/website/docs/r/acl_token.html.markdown).

## Example usage

```hcl
data "nomad_acl_token" "my_token" {
  accessor_id = "aa534e09-6a07-0a45-2295-a7f77063d429"
}
```

## Argument reference

* `accessor_id`: `(string)` Non-sensitive identifier for this token.

## Attributes reference

* `name`: `(string)` Human-friendly name of the ACL token.
* `accessor_id`: `(string)` Non-sensitive identifier for this token.
* `secret_id`: `(string)` The token value itself.
* `type`: `(string)` The type of the token.
* `policies`: `(list of strings)` List of policy names associated with this token.
* `global`: `(bool)` Whether the token is replicated to all regions, or if it will only be used in the region it was created.
* `create_time`: `(string)` Date and time the token was created.

**Comment by softpunks** [comment]
👋 Hi I'm Maxine, and I would love to take a crack at this issue if that is alright. 😄

**Comment by lgfa29** [comment]
Great, welcome aboard @softpunks  :)

Feel free to start working on this. We can help validate your code as you work through it, so feel free to reach out if you need any help.

**Comment by softpunks** [comment]
^ I think that PR should handle it. let me know if you have any feedback or changes
