### ISSUE TITLE
Create data source for listing ACL tokens

### ISSUE THREAD

**Issue by lgfa29** [terraform-providers/terraform-provider-nomad#86]
# nomad_acl_tokens

Get a list of [ACL tokens](https://www.nomadproject.io/api/acl-tokens.html#list-tokens).

**Important:** this data source will store tokens in the Terraform state. The documentation should have a warning like the [one in the resource page](https://github.com/terraform-providers/terraform-provider-nomad/blob/master/website/docs/r/acl_token.html.markdown).

## Example usage

```hcl
data "nomad_acl_tokens" "tokens" {
  prefix = "a242"
}
```

## Argument reference

* `prefix`: `(string)` Filter ACL tokens based on this accessor ID prefix.

## Attributes reference

* `acl_tokens`: `(list of map)`List of ACL tokens
  * `name`: `(string)` Human-friendly name of the ACL token.
  * `accessor_id`: `(string)` Non-sensitive identifier for this token.
  * `type`: `(string)` The type of the token.
  * `policies`: `(list of strings)` List of policy names associated with this token.
  * `global`: `(bool)` Whether the token is replicated to all regions, or if it will only be used in the region it was created.
  * `create_time`: `(string)` Date and time the token was created.

**Comment by adharmawan** [comment]
I would like to take this as well :)

**Comment by lgfa29** [comment]
@adharmawan go for it :)

Let us know if you have any questions.

**Comment by remilapeyre** [comment]
It seems like no pull requests have been submitted for this, @andyyaldoo if your are not working on this, I can submit a pull request.

>Important: this data source will store tokens in the Terraform state. The documentation should have a warning like the one in the resource page.

I think we could do the same thing that what we did in the Consul provider, which is having a `[consul_acl_token](https://www.terraform.io/docs/providers/consul/d/acl_token.html)` resource that fetch the public information associated with a token and a `[consul_acl_token_secret_id](https://www.terraform.io/docs/providers/consul/d/acl_token_secret_id.html)` that only gets the secret id. That way, you can still reference a token without saving the secret id in the tfstate if you only need it's name or the policies attached.

**Comment by lgfa29** [comment]
That's a good idea @remilapeyre, thanks for bringing it up to us. Since there haven't been any activity on this issue I will assign it to you.

@andyyaldoo thank you for your work so far. I hope it's OK to pass this on to @remilapeyre, but feel free to reach out if you are still interested.

**Comment by cgbaker** [comment]
alternatively, @remilapeyre , there could be an attribute `(default: false)` which instructs the provider to not persist the secret IDs.

**Comment by lgfa29** [comment]
@cgbaker `default: false` meaning storing the SecretID is opt-in, so it won't be stored by default?

**Comment by cgbaker** [comment]
that's what I meant... too many negatives:
`fetch_secret_id: boolean (default: false)`

**Comment by remilapeyre** [comment]
Hi I just opened a PR, the API endpoint that list the tokens does not give the `secret_id` so another API call for every token would be needed to fetch it. I did not implemented that as it is already possible to have this behavior by combining `nomad_acl_tokens` and `nomad_acl_token`. Let me know if you want me to change this.
