### ISSUE TITLE
Create data source for Namespace

### ISSUE THREAD

**Issue by lgfa29** [terraform-providers/terraform-provider-nomad#87]
# nomad_namespace

Get information on a [namespace](https://www.nomadproject.io/api/namespaces.html#read-namespace). 

## Example usage

```hcl
data "nomad_namespace" "dev" {
  name = "dev"
}
```

## Argument reference

* `name`: `(string)` Human-friendly name of the namespace.

## Attributes reference

* `name`: `(string)` Human-friendly name of the namespace.
* `description`: `(string)` A description of the namespace.
* `quota`: `(string)` A resource quota attached to the namespace.
* `hash`: `(string)` The namespace hash.

_Note: Namespaces are an enterprise feature. You will need to use a release with the `+ent` flag from https://releases.hashicorp.com/nomad/_

**Comment by softpunks** [comment]
I can take a crack at this ✋

**Comment by lgfa29** [comment]
Awesome, thanks @softpunks 😄 

This one will be a little trickier than the previous ones because namespaces is an Enterprise feature, so you will have to work around that (for example, mocking the API based on our [docs sample response](https://www.nomadproject.io/api/namespaces.html#sample-response-1)).

We can help you test cases not covered in the docs, so feel free to reach out if you need any help.

**Comment by remilapeyre** [comment]
> This one will be a little trickier than the previous ones because namespaces is an Enterprise feature, so you will have to work around that (for example, mocking the API based on our [docs sample response](https://www.nomadproject.io/api/namespaces.html#sample-response-1)).

@lgfa29  You can use the binaries at https://releases.hashicorp/com marked with `+ent` to try the enterprise features, you should get a few hours to work on it before the cluster locks itself up.

If you don't work on this issue anymore I can send a PR.

**Comment by lgfa29** [comment]
That wasn't true for Nomad until a few weeks ago when we added support for licensing in `0.12.0-beta2` https://releases.hashicorp.com/nomad/ 😄 

But you are right, it should be easier to work on this now. I will re-assign this to you and update the issue to point to the enterprise binaries.

@softpunks thank you for all your work on other issues!
