### ISSUE TITLE
Provider doesn't recognize env key in template stanza.

### ISSUE THREAD

**Issue by CGreenburg** [terraform-providers/terraform-provider-nomad#9]
### Terraform Version
0.10.2

### Affected Resource(s)
- nomad_job

### Terraform Configuration Files
```hcl
provider "nomad" {
	address = "${var.nomad_addr}"
}

resource "nomad_job" "example" {
	jobspec = "${file("${path.module}/deploy.nomad.tpl")}"
}
```

### Debug Output
https://gist.github.com/CGreenburg/cdad7b78e70faee8e08689b7c16fc640

### Expected Behavior
Terraform should create the nomad job.

### Actual Behavior
Terraform fails to create the nomad job. I assume this is because this provider is using an older version of the jobspec library that Nomad provides. My Nomad deploy file uses the environment variable template stanza syntax: https://www.nomadproject.io/docs/job-specification/template.html#environment-variables. This is where the error is happening

**Comment by cstruct** [comment]
I think #7 should fix this.

**Comment by CGreenburg** [comment]
You're right. I should have checked the open pull requests. Thanks.
