### ISSUE TITLE
connect sidecar_service does not support tags

### ISSUE THREAD

**Issue by Legogris** [terraform-providers/terraform-provider-nomad#96]
### Terraform Version

Terraform v0.12.20
+ provider.nomad v1.4.3
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Nomad Version
0.10.2

```
group "abc" {
  service {
    connect {
      sidecar_service {
        tags = []
      }
    }
  }
}
```
```
Error: error parsing jobspec: error parsing 'job': group: 'abc', service (0): 'abc', sidecar_service, 1 error occurred:
        * sidecar_service -> invalid key: tags
```

`sidecar_service` supports tags and this is necessary to avoid collisions on routes when configuring load balancers such as Fabio and traefik.

https://www.nomadproject.io/docs/job-specification/sidecar_service.html
https://github.com/hashicorp/nomad/issues/6757

**Comment by cgbaker** [comment]
thanks for the report, we'll look at this today.

**Comment by cgbaker** [comment]
will immediately release 1.4.4 with this change
