### ISSUE TITLE
upgrade Nomad dependancy once Nomad 0.11.0 is released

### ISSUE THREAD

**Issue by jrasell** [terraform-providers/terraform-provider-nomad#98]
The Nomad 0.11.0-beta1 was recently released with a lot of new features, including new jobspec stanzas. Once the 0.11.0 release goes live, the provider should be updated to track the latest version.

**Comment by cgbaker** [comment]
i've got a few changes still in flight for the API (mostly around the scaling API), then we can take care of this.

**Comment by raypettersen** [comment]
Any traction on this? We're testing the RC and are a bit stuck atm.

**Comment by cgbaker** [comment]
i was waiting on an API fix which just shipped with nomad 0.11.0-rc1
i will release 1.4.5 today with support for the 0.11.0 API

**Comment by cgbaker** [comment]
release pipeline in flight, should be available in a little bit.

**Comment by cgbaker** [comment]
done! enjoy! 🎉
